imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

lexik_jwt_authentication:
    secret_key: "%kernel.root_dir%/../var/jwt/private.pem"
    public_key: "%kernel.root_dir%/../var/jwt/public.pem"
    pass_phrase: "%jwt_key_pass_phrase%"
    token_ttl: 216000
