user:
    resource: '@UserBundle/Resources/config/routing.yml'
    prefix: /api

event:
    resource: '@EventBundle/Resources/config/routing.yml'
    prefix: /api

security:
    resource: '@CustomSecurityBundle/Resources/config/routing.yml'
    prefix: /api

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'