EventBundle\Entity\Appointment:
    type: entity
    repositoryClass: EventBundle\Repository\AppointmentRepository
    manyToMany:
        invitedUsers:
            targetEntity:  UserBundle\Entity\User
            invdersedBy: appointments
            cascade: ["persist"]
            joinColumns:
                appointment_id:
                    referencedColumnName: id
            inverseJoinColumns:
                user_id:
                    referencedColumnName: id
