UserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            nullable: false
        lastName:
            type: string
            nullable: false
    oneToMany:
        events:
            targetEntity: EventBundle\Entity\Event
            mappedBy: user
    manyToMany:
        appointments:
            targetEntity: EventBundle\Entity\Appointment
            mappedBy: invitedUsers