UserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            groups: [default, create, view, update]
        email:
            type: string
            groups: [default, create, view, update]
        username:
            type: string
            groups: [default, create, view, update]
        firstName:
            type: string
            serialized_name: firstName
            groups: [default, create, view, update]
        lastName:
            type: string
            serialized_name: lastName
            groups: [default, create, view, update]
        appointments:
            type: ArrayCollection<EventBundle\Entity\Appointment>
            groups: [detail]