EventBundle\Entity\Reminder:
    properties:
        title:
            - Type :
                type: string
                groups: [create, update]
            - Length:
                min: 5
                minMessage: 'Title must be at least {{ limit }} characters long'
                groups: [create, update]
            - NotBlank:
                groups: [create, update]
        description:
            - Type :
                type: string
                groups: [create, update]
            - Length:
                min: 10
                minMessage: 'Description must be at least {{ limit }} characters long'
                groups: [create, update]
            - NotBlank:
                groups: [create, update]
        startDateTime:
            - DateTime : ~
            - NotBlank:
                groups: [create, update]
        endDateTime:
            - DateTime : ~
            - NotBlank:
                groups: [create, update]