EventBundle\Entity\Appointment:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            groups: [default, create, update]
        title:
            type: string
            groups: [default, create, update]
        description:
            type: string
            groups: [default, create, update]
        startDateTime:
            type: DateTime<'d.m.Y H:i:s'>
            serialized_name: startDateTime
            groups: [default, create, update]
        endDateTime:
            type: DateTime<'d.m.Y H:i:s'>
            serialized_name: endDateTime
            groups: [default, create, update]
        user:
            type: UserBundle\Entity\User
            max_depth: 0
            access_type: public_method
            accessor:
                getter: getUser
                setter: setUser
            groups: [default, create, update]
        invitedUsers:
            type: ArrayCollection<UserBundle\Entity\User>
            serialized_name: invitedUsers
            max_depth: 0
            groups: [default, create, update]